export const cardStyles = {
    base: 'depth-card group theme-radius-card border theme-border theme-surface shadow-sm theme-interactive',
    hover: 'theme-hover-surface theme-hover-lift',
    gridPadding: 'p-4 sm:p-5',
    listPadding: 'p-4',
    gridLayout: 'space-y-3.5 sm:space-y-4',
    listLayout: 'flex flex-col gap-4 md:flex-row md:items-center md:justify-between',
    contentGrid: 'min-w-0 flex-1 md:pr-4',
    contentGridDefault: 'space-y-3.5 sm:space-y-4',
    headerRow: 'flex items-start justify-between gap-3',
    metaGrid: 'grid grid-cols-1 gap-2.5 sm:grid-cols-2',
    metaList: 'grid grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-4',
    actionAreaGrid: 'space-y-3.5 sm:space-y-4',
    actionAreaList: 'flex w-full items-center gap-3 border-t theme-border pt-3 md:w-auto md:border-t-0 md:border-l md:pl-4 md:pt-0',
    tagRow: 'flex flex-wrap items-center gap-2',
    menuPanel: 'absolute right-0 top-9 z-20 w-44 rounded-xl border theme-border theme-surface p-1 shadow-lg',
    menuItem: 'w-full rounded-lg px-3 py-2 text-left text-sm theme-text-secondary theme-interactive theme-hover-surface hover:theme-text-primary',
    menuItemDanger: 'w-full rounded-lg px-3 py-2 text-left text-sm theme-tone-danger hover:bg-[var(--qb-danger-soft)]',
    metricGrid: 'grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4',
    metricCard: 'rounded-3xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800',
    billingHero: 'flex flex-col items-center justify-between gap-8 rounded-[2.5rem] border border-[color-mix(in_srgb,var(--qb-primary)_26%,var(--qb-border))] bg-linear-to-r from-[color-mix(in_srgb,var(--qb-primary)_12%,var(--qb-surface-1))] to-[color-mix(in_srgb,var(--qb-accent)_12%,var(--qb-surface-1))] p-8 shadow-sm md:flex-row dark:from-gray-800 dark:to-[color-mix(in_srgb,var(--qb-primary)_28%,var(--qb-surface-1))]',
    billingCard: 'space-y-6 rounded-[2.5rem] border border-gray-100 bg-white p-8 shadow-sm dark:border-gray-700 dark:bg-gray-800',
    billingSubCard: 'rounded-[1.5rem] border border-gray-100 bg-slate-50 px-4 py-5 dark:border-gray-700 dark:bg-gray-700/50',
    infoRow: 'flex items-center justify-between rounded-2xl bg-slate-50 px-4 py-3 dark:bg-gray-700/50',
    dashedInfo: 'rounded-2xl border border-dashed theme-status-info px-4 py-3 text-xs font-bold',
    paymentEntry: 'grid grid-cols-1 gap-3 rounded-2xl border border-gray-100 bg-slate-50 px-4 py-4 text-sm font-bold md:grid-cols-5 dark:border-gray-700 dark:bg-gray-700/50 dark:text-gray-200',
    emptyDashed: 'rounded-[2rem] border border-dashed border-gray-200 px-6 py-10 text-center text-sm font-bold text-slate-400 dark:border-gray-700 dark:text-gray-500',
    usageCard: 'relative overflow-hidden rounded-[2rem] border border-gray-100 p-6 shadow-sm transition-colors dark:border-gray-700 dark:bg-gray-800',
    usageOrb: 'absolute -right-4 -top-4 h-24 w-24 rounded-bl-full opacity-50 transition-transform group-hover:scale-110',
    statusCardBase: 'rounded-2xl border-2 p-6',
    leaderboardEntry: 'flex items-center justify-between p-5',
    leaderboardIdentity: 'flex items-center gap-5',
    leaderboardRank: 'text-2xl font-black',
    leaderboardPlayer: 'text-lg font-black uppercase leading-none tracking-tight text-slate-900 dark:text-gray-100',
    leaderboardScore: 'text-2xl font-black leading-none text-slate-900 dark:text-gray-100',
    leaderboardFooter: 'border-t border-gray-100 bg-gray-50 p-6 text-center font-black uppercase text-slate-900 dark:border-gray-700 dark:bg-gray-700/40 dark:text-gray-100',
    usageGrid: 'grid grid-cols-1 gap-6 sm:grid-cols-2',
    usageProgressWrap: 'relative mt-4 h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-gray-700',
    usageProgressFill: 'h-full rounded-full',
    iconTextRow: 'flex items-center justify-between',
    valueRow: 'flex items-end gap-2',
    detailGrid2: 'grid grid-cols-2 gap-4',
    borderedTop: 'mt-4 border-t border-current border-opacity-20 pt-4',
    stackSm: 'space-y-3',
    stackMdStrong: 'space-y-4 text-sm font-bold',
    keyValueRow: 'flex items-end gap-3 font-bold text-slate-800 dark:text-gray-100',
};
