export const components = {
    button: {
        base: 'inline-flex items-center justify-center rounded-lg font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60',
        sizes: {
            sm: 'h-8 px-3 text-xs',
            md: 'h-10 px-4 text-sm',
            lg: 'h-11 px-5 text-sm',
        },
        variants: {
            primary: 'bg-indigo-600 text-white hover:bg-indigo-500 focus-visible:ring-indigo-500',
            secondary: 'bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-100 dark:hover:bg-gray-700 focus-visible:ring-gray-400',
            ghost: 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800 focus-visible:ring-gray-400',
            danger: 'bg-red-600 text-white hover:bg-red-500 focus-visible:ring-red-500',
        },
    },
    modal: {
        overlay: 'fixed inset-0 z-[var(--z-modal)] bg-gray-900/60 backdrop-blur-sm',
        panel: 'w-full max-w-2xl rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 shadow-xl',
        header: 'px-6 py-4 border-b border-gray-200 dark:border-gray-700',
        body: 'px-6 py-5',
        footer: 'px-6 py-4 border-t border-gray-200 dark:border-gray-700 flex items-center justify-end gap-3',
    },
    badge: {
        neutral: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300',
        success: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
        warning: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
        danger: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
        info: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300',
    },
    divider: 'border-t border-gray-200 dark:border-gray-700',
    panel: 'rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 shadow-sm',
    analytics: {
        card: 'rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800',
        cardCompact: 'rounded-2xl border border-gray-200 bg-white p-4 md:p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800',
        subtleCard: 'rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-600 dark:bg-gray-700/50',
        sectionTitleUpper: 'text-sm font-semibold text-gray-700 uppercase tracking-wide dark:text-gray-300',
        sectionTitleMeta: 'text-xs text-gray-400 uppercase tracking-wide dark:text-gray-500',
        metricLabel: 'text-xs text-gray-400 uppercase tracking-wide dark:text-gray-500',
        metricValue: 'mt-2 text-lg font-semibold text-gray-900 dark:text-gray-100',
        metricValue2Xl: 'mt-2',
        metricCaption: 'mt-1',
        cardStack: 'space-y-4',
        emptyState: 'text-sm text-slate-500 dark:text-gray-400',
        chartHeightLg: 'mt-4 h-80',
        chartHeightMd: 'mt-4 h-72',
        tableWrap: 'mt-4 overflow-x-auto',
        table: 'min-w-full text-left text-sm',
        tableHeadRow: 'border-b border-gray-200 text-xs text-gray-400 dark:border-gray-700 dark:text-gray-500',
        tableHeadCell: 'py-2 pr-3',
        tableBodyRowEven: 'bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700',
        tableBodyRowOdd: 'bg-gray-50/70 dark:bg-gray-700/40 border-b border-gray-100 dark:border-gray-700',
        tableBodyCellStrong: 'py-2 pr-3 font-semibold text-slate-700 dark:text-gray-100',
        tableBodyCell: 'py-2 pr-3 text-gray-600 dark:text-gray-300',
        stackSm: 'mt-4 space-y-3',
        rowBetween: 'flex items-center justify-between',
        textStrong: 'text-sm font-medium text-gray-700 dark:text-gray-300',
        textDanger: 'text-sm font-medium text-rose-600 dark:text-rose-300',
        loadingCard: 'rounded-2xl border border-gray-200 bg-white p-4 md:p-6 text-center text-sm text-gray-600 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400',
    },
    profile: {
        loadingPage: 'app-page',
        page: 'app-page space-y-4',
        loadingText: 'text-slate-500 font-medium dark:text-gray-400',
        cardStack: 'p-4 space-y-4',
        rowBetween: 'flex flex-wrap items-center justify-between gap-4',
        identityWrap: 'flex items-center gap-5',
        avatar: 'w-20 h-20 rounded-full overflow-hidden bg-indigo-50 border border-gray-200 flex items-center justify-center text-indigo-600 text-sm font-medium dark:border-gray-600 dark:bg-indigo-900/30 dark:text-indigo-300',
        avatarImage: 'w-full h-full object-cover',
        titleRow: 'text-sm font-medium text-gray-900 flex items-center gap-3 dark:text-gray-100',
        roleBadge: 'text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded-md self-start dark:bg-gray-700 dark:text-gray-300',
        planBadgeBase: 'text-xs px-2 py-0.5 rounded-md self-start',
        planFree: 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300',
        planPremium: 'bg-slate-900 text-yellow-400 dark:bg-yellow-900/30 dark:text-yellow-300',
        planPro: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300',
        email: 'text-sm text-gray-600 dark:text-gray-400',
        statCard: 'bg-white border border-gray-200 rounded-2xl shadow-sm p-4 dark:bg-gray-800 dark:border-gray-700',
        statLabel: 'text-xs uppercase tracking-wide text-gray-400 dark:text-gray-500',
        statValue: 'mt-1 text-sm font-medium text-gray-900 wrap-break-word dark:text-gray-100',
        sectionHeading: 'space-y-1',
        sectionSubText: 'mt-1 text-sm text-gray-600 dark:text-gray-400',
        sectionStack: 'space-y-4',
        statGrid: 'grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3',
    },
    studio: {
        pageShell: 'app-page animate-in fade-in duration-500',
        controlBar: 'w-full rounded-xl border border-gray-200/90 bg-white px-3 py-3 shadow-sm md:px-4 dark:border-gray-700 dark:bg-gray-800',
        controlInner: 'flex items-center justify-between gap-4 md:gap-6 flex-wrap',
        headingWrap: 'min-w-0 space-y-0.5',
        crumb: 'text-xs text-gray-400 dark:text-gray-500',
        title: 'text-xl md:text-2xl font-semibold tracking-tight text-slate-900 dark:text-gray-100',
        subtitle: 'text-sm text-gray-500 leading-5 dark:text-gray-400',
        centerControlsWrap: 'order-3 w-full md:order-2 md:w-auto md:flex-1 md:justify-center md:flex',
        segmentedShell: 'flex items-center gap-1.5 overflow-x-auto rounded-xl border border-gray-200 bg-gray-50/90 px-1.5 py-1 dark:border-gray-700 dark:bg-gray-700/60',
        segmentedInner: 'inline-flex items-center rounded-lg bg-transparent p-0.5',
        modeBtnBase: 'inline-flex h-8 items-center gap-1.5 rounded-md px-2.5 text-sm font-medium transition-all',
        modeBtnActive: 'bg-white text-slate-900 shadow-sm dark:bg-gray-800 dark:text-gray-100',
        modeBtnIdle: 'text-gray-500 hover:text-slate-700 dark:text-gray-400 dark:hover:text-gray-200',
        modeBtnDisabled: 'disabled:cursor-not-allowed disabled:opacity-50',
        sortFilterLabel: 'inline-flex h-8 items-center gap-1.5 rounded-md px-2.5 text-sm font-medium text-gray-600 hover:bg-white dark:text-gray-300 dark:hover:bg-gray-700',
        sortFilterSelect: 'bg-transparent text-sm font-medium text-slate-900 outline-none dark:text-gray-100',
        actionWrap: 'order-2 ml-auto sticky bottom-3 flex w-full items-center justify-end gap-2 rounded-xl bg-white/95 p-1.5 shadow-sm md:order-3 md:static md:w-auto md:bg-transparent md:p-0 md:shadow-none dark:bg-gray-800/95',
        searchInput: 'h-9 w-50 rounded-xl border border-gray-300 bg-white px-3 text-sm text-gray-900 outline-none transition-all duration-200 placeholder:text-gray-400 focus:border-indigo-300 focus:shadow-[0_0_0_3px_rgba(99,102,241,0.12)] focus:w-57.5 md:w-65 md:focus:w-75 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100 dark:placeholder:text-gray-500',
        newBtn: 'inline-flex h-9 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-medium text-white shadow-sm transition-colors hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600',
    },
    organizer: {
        loading: 'min-h-screen bg-(--color-dark) flex flex-col items-center justify-center text-slate-400 dark:text-gray-500',
        header: 'min-h-16 border-b border-gray-200 bg-white backdrop-blur-md flex items-center justify-between px-6 py-2 shrink-0 dark:border-gray-700 dark:bg-gray-900',
        headerLeft: 'flex items-center gap-4',
        titleClamp: 'max-w-136 wrap-break-word leading-tight',
        navBack: 'bg-white border border-gray-200 text-slate-600 hover:bg-gray-50 hover:text-slate-900 focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-gray-100',
        headerActions: 'flex items-center gap-4',
        tabShell: 'inline-flex rounded-xl border border-gray-200 bg-gray-100 p-1 dark:border-gray-700 dark:bg-gray-800',
        tabActive: 'rounded-lg text-xs px-5 py-1.5 shadow-sm',
        tabBtn: 'rounded-lg px-5 py-1.5 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors dark:text-gray-300 dark:hover:text-gray-100',
        tabBtnWithIcon: 'rounded-lg px-5 py-1.5 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors inline-flex items-center gap-1 dark:text-gray-300 dark:hover:text-gray-100',
        saveBtn: 'inline-flex items-center gap-2 px-6 py-2 text-xs rounded-xl shadow-sm transition-all',
        launchBtn: 'inline-flex items-center gap-2 px-6 py-2 text-xs rounded-xl shadow-sm transition-all',
        errorWrap: 'app-page fixed top-17 left-2 right-2 z-60',
        importShell: 'oe-import-shell',
        aiPromptHeader: 'flex items-center justify-between gap-3',
        aiPromptCopyBtn: 'rounded-xl px-4 py-2 text-sm font-semibold text-indigo-700 hover:bg-indigo-50 dark:text-indigo-300 dark:hover:bg-gray-700',
        aiPromptCode: 'mt-4 max-h-56 overflow-auto whitespace-pre-wrap rounded-2xl border border-gray-200 bg-white p-4 text-sm text-slate-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-200',
        spin: 'animate-spin',
        aiSkeleton: 'h-20 animate-pulse rounded-xl border border-gray-100 bg-gray-50 dark:border-gray-700 dark:bg-gray-700/40',
        aiQuestionHeader: 'flex items-center justify-between gap-2',
        aiQuestionCardPad: 'p-4',
        aiQuestionDifficulty: 'rounded-full bg-gray-100 px-2 py-1 text-[10px] font-black uppercase tracking-widest text-slate-600 dark:bg-gray-700 dark:text-gray-300',
        aiOptionGrid: 'mt-3 grid grid-cols-1 gap-2 md:grid-cols-2',
        aiOptionBase: 'rounded-lg border px-3 py-2 text-sm font-semibold',
        aiOptionCorrect: 'border-emerald-300 bg-emerald-50 text-emerald-700 dark:border-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
        aiOptionWrong: 'border-gray-200 bg-gray-50 text-slate-600 dark:border-gray-600 dark:bg-gray-700/40 dark:text-gray-300',
        aiExplainMargin: 'mt-3',
        aiExplainLabel: 'font-bold uppercase tracking-widest',
        aiGenerateBtn: 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold shadow-sm disabled:cursor-not-allowed disabled:opacity-60',
        aiActionBtn: 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-60',
        editorRoot: 'fixed inset-0 z-50 bg-white flex flex-col animate-in fade-in duration-300',
        editorBody: 'flex flex-1 overflow-hidden',
        slideAside: 'w-64 bg-white shrink-0 border-r border-gray-200 flex flex-col focus-visible:ring-2 focus-visible:ring-indigo-500',
        slideTopPad: 'p-4',
        slideAddBtn: 'w-full inline-flex items-center justify-center gap-2',
        slideListWrap: 'flex-1 overflow-y-auto px-4 pb-4 space-y-4',
        slideItem: 'group cursor-pointer flex w-full flex-col gap-2 text-left focus-visible:ring-2 focus-visible:ring-indigo-500 rounded-lg',
        slideItemRow: 'flex gap-3 items-center relative pr-9',
        slideIndex: 'text-xs text-gray-400 dark:text-gray-500',
        slideThumb: 'flex-1 aspect-video rounded-lg border-2 transition-all p-2 flex flex-col justify-center items-center gap-1 overflow-hidden',
        slideThumbActive: 'border-indigo-500 bg-white shadow-sm',
        slideThumbIdle: 'border-gray-200 bg-gray-50 hover:border-gray-200',
        slideBarStrong: 'w-full h-1 bg-slate-400 rounded-full',
        slideBarSoft: 'w-2/3 h-1 bg-slate-300 rounded-full',
        slideMiniGrid: 'grid grid-cols-2 gap-1 w-full mt-1',
        slideMiniCell: 'h-1 bg-slate-800 rounded-full',
        slideActionBase: 'absolute right-0 opacity-0 group-hover:opacity-100 p-1.5 text-slate-500 transition-all rounded-lg focus-ring',
        slideActionTop: '-top-0.5 hover:text-slate-900 hover:bg-gray-100 disabled:opacity-35 disabled:cursor-not-allowed',
        slideActionMid: 'top-1/2 -translate-y-1/2 hover:text-red-500 hover:bg-red-500/10',
        slideActionBottom: '-bottom-0.5 hover:text-slate-900 hover:bg-gray-100 disabled:opacity-35 disabled:cursor-not-allowed',
        configAside: 'w-80 bg-white shrink-0 border-l border-gray-200 p-6 overflow-y-auto space-y-8',
        configSection: 'space-y-6',
        configTitle: 'pl-1',
        configStack: 'space-y-4',
        configToggleBtn: 'w-full flex items-center justify-between gap-4 px-4 py-3 rounded-xl border transition-all disabled:opacity-50 disabled:cursor-not-allowed',
        configToggleOnSuccess: 'bg-emerald-50 border-emerald-200 text-emerald-700',
        configToggleOnWarning: 'bg-orange-50 border-orange-200 text-orange-700',
        configToggleOff: 'bg-gray-100 border-transparent text-slate-600 hover:bg-gray-200',
        configToggleLabel: 'text-xs font-bold uppercase tracking-widest',
        configSwitchTrack: 'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
        configSwitchTrackOnSuccess: 'bg-emerald-500',
        configSwitchTrackOnWarning: 'bg-orange-500',
        configSwitchTrackOff: 'bg-slate-300',
        configSwitchThumb: 'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
        configSwitchThumbOn: 'translate-x-6',
        configSwitchThumbOff: 'translate-x-1',
        configHint: 'px-1',
        configField: 'space-y-2',
        configSelectNative: 'appearance-none pr-10',
        configApplyBtn: 'w-full disabled:opacity-50 disabled:cursor-not-allowed',
        configDividerTop: 'border-t border-gray-200 pt-6 space-y-4',
        configSelectWrap: 'relative',
        configSelectIconWrap: 'absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50',
        iconAccent: 'fill-indigo-500 text-indigo-500',
        configFooter: 'pt-8 border-t border-gray-200',
        configDeleteBtn: 'w-full inline-flex items-center justify-center gap-2',
        canvasMain: 'flex-1 bg-linear-to-br from-slate-100 to-slate-200 p-10 overflow-y-auto flex flex-col items-center',
        canvasCard: 'w-full max-w-5xl aspect-video bg-white rounded-[28px] px-12 py-10 shadow-lg border border-slate-200 relative flex flex-col',
        canvasHeader: 'flex items-center justify-between mb-6',
        canvasHeaderLeft: 'flex items-center gap-2',
        canvasSlidePill: 'inline-flex items-center px-3 py-1.5 rounded-lg bg-indigo-50 text-indigo-600 text-xs font-bold uppercase tracking-widest',
        canvasHeaderIcon: 'opacity-10',
        canvasContent: 'flex flex-col flex-1',
        canvasRow: 'flex items-start gap-6 flex-1',
        canvasBadgeCol: 'mt-1 min-w-12 h-fit',
        canvasBadge: 'flex items-center justify-center w-12 h-12 rounded-lg bg-indigo-500 text-white font-bold text-lg shadow-md',
        canvasQuestionCol: 'flex flex-col gap-6 flex-1 max-w-3xl',
        canvasQuestionInput: 'w-full bg-transparent resize-none rounded-lg focus-visible:ring-2 focus-visible:ring-indigo-500 text-xl md:text-2xl font-semibold text-slate-900 placeholder:text-slate-300 leading-snug text-left',
        canvasOptionsGrid: 'grid grid-cols-2 gap-4 w-full',
        canvasOptionCard: 'relative group transition-all duration-200 hover:scale-[1.02]',
        canvasOptionBadge: 'absolute -top-3 left-3 px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-full flex items-center gap-1.5 shadow-md z-10',
        canvasOptionBadgeCorrect: 'bg-green-500 text-white',
        canvasOptionBadgeIdle: 'bg-slate-700 text-white',
        canvasOptionBadgeLetter: 'w-5 h-5 rounded-full bg-white/30 flex items-center justify-center text-xs font-black',
        canvasOptionButton: 'w-full h-20 px-5 rounded-xl font-semibold text-left text-sm transition-all duration-200 border-2 shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 flex items-center gap-3 cursor-text',
        canvasOptionButtonCorrect: 'bg-linear-to-r from-green-50 to-emerald-50 border-green-400 shadow-inner',
        canvasOptionButtonIdle: 'bg-slate-50 border-slate-200 hover:border-indigo-400 hover:bg-indigo-50/30 focus-within:border-indigo-500 focus-within:ring-2 focus-within:ring-indigo-100',
        canvasOptionInput: 'flex-1 bg-transparent border-none text-slate-800 placeholder:text-slate-400 focus-visible:ring-2 focus-visible:ring-indigo-500 rounded',
        canvasEmpty: 'flex flex-col items-center justify-center flex-1 text-center text-slate-400 space-y-4',
        canvasEmptyText: 'text-lg font-medium',
        canvasEmptySub: 'text-sm text-slate-400',
        canvasFooter: 'mt-6 text-[10px] tracking-widest uppercase text-slate-400',
    },
};
