export const components = {
    appShell: 'app-shell',
    appMain: 'app-main',
    ui: {
        glowOrb: 'absolute left-1/2 top-[-15%] h-[600px] w-[600px] -translate-x-1/2 rounded-full bg-[color-mix(in_srgb,var(--qb-primary)_14%,transparent)] blur-[90px] pointer-events-none',
    },
    button: {
        base: 'inline-flex items-center justify-center rounded-lg font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60',
        sizes: {
            sm: 'h-8 px-3 text-xs',
            md: 'h-10 px-4 text-sm',
            lg: 'h-11 px-5 text-sm',
        },
        variants: {
            primary: 'bg-[var(--qb-primary)] text-white hover:bg-[var(--qb-primary-strong)] focus-visible:ring-[var(--qb-primary)]',
            secondary: 'theme-surface-soft theme-text-primary hover:opacity-90 focus-visible:ring-[var(--qb-primary)]',
            ghost: 'theme-text-secondary hover:theme-surface-soft focus-visible:ring-[var(--qb-primary)]',
            danger: 'bg-[var(--qb-danger-ink)] text-white hover:opacity-90 focus-visible:ring-[var(--qb-danger-ink)]',
        },
    },
    modal: {
        overlay: 'fixed inset-0 z-[var(--z-modal)] bg-gray-900/60 backdrop-blur-sm',
        panel: 'w-full max-w-2xl rounded-2xl border theme-border theme-surface shadow-xl',
        header: 'px-6 py-4 border-b theme-border',
        body: 'px-6 py-5',
        footer: 'px-6 py-4 border-t theme-border flex items-center justify-end gap-3',
    },
    commandPalette: {
        overlay: 'fixed inset-0 z-[var(--z-modal)] bg-gray-900/55 backdrop-blur-sm',
        wrap: 'mx-auto mt-20 w-full max-w-2xl px-4',
        panel: 'rounded-2xl border theme-border theme-surface shadow-2xl',
        searchRow: 'flex items-center gap-3 border-b theme-border px-4 py-3',
        searchIcon: 'theme-text-muted',
        searchInput: 'h-10 w-full bg-transparent text-sm theme-text-primary outline-none placeholder:theme-text-muted',
        hint: 'shrink-0 rounded-md border theme-border theme-surface-soft px-2 py-1 text-[11px] font-semibold theme-text-muted',
        list: 'max-h-96 overflow-y-auto p-2',
        item: 'flex w-full items-start justify-between gap-3 rounded-xl px-3 py-2.5 text-left transition-colors',
        itemActive: 'bg-[color-mix(in_srgb,var(--qb-primary)_14%,var(--qb-surface-1))] text-[var(--qb-primary)]',
        itemIdle: 'theme-text-secondary hover:theme-surface-soft',
        itemTextWrap: 'min-w-0',
        itemTitle: 'text-sm font-semibold',
        itemDesc: 'mt-0.5 text-xs theme-text-muted',
        itemMeta: 'shrink-0 rounded-md border theme-border theme-surface px-2 py-1 text-[11px] font-medium theme-text-muted',
        footer: 'flex items-center justify-between border-t theme-border px-4 py-2 text-xs theme-text-muted',
        empty: 'rounded-xl border border-dashed theme-border px-4 py-8 text-center text-sm theme-text-muted',
    },
    badge: {
        neutral: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300',
        success: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium theme-status-success',
        warning: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium theme-status-warning',
        danger: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium theme-status-danger',
        info: 'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300',
    },
    divider: 'border-t theme-border',
    panel: 'rounded-xl border theme-border theme-surface shadow-sm',
    analytics: {
        card: 'rounded-2xl border theme-border theme-surface p-5 shadow-sm',
        cardCompact: 'rounded-2xl border theme-border theme-surface p-4 md:p-6 shadow-sm',
        subtleCard: 'rounded-xl border theme-border theme-surface-soft p-4',
        sectionTitleUpper: 'text-sm font-semibold text-gray-700 uppercase tracking-wide dark:text-gray-300',
        sectionTitleMeta: 'text-xs text-gray-400 uppercase tracking-wide dark:text-gray-500',
        metricLabel: 'text-xs text-gray-400 uppercase tracking-wide dark:text-gray-500',
        metricValue: 'mt-2 text-lg font-semibold text-gray-900 dark:text-gray-100',
        metricValue2Xl: 'mt-2',
        metricCaption: 'mt-1',
        cardStack: 'space-y-4',
        emptyState: 'text-sm text-slate-500 dark:text-gray-400',
        chartHeightLg: 'mt-4 h-80',
        chartHeightMd: 'mt-4 h-72',
        tableWrap: 'mt-4 overflow-x-auto',
        table: 'min-w-full text-left text-sm',
        tableHeadRow: 'border-b border-gray-200 text-xs text-gray-400 dark:border-gray-700 dark:text-gray-500',
        tableHeadCell: 'py-2 pr-3',
        tableBodyRowEven: 'bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700',
        tableBodyRowOdd: 'bg-gray-50/70 dark:bg-gray-700/40 border-b border-gray-100 dark:border-gray-700',
        tableBodyCellStrong: 'py-2 pr-3 font-semibold text-slate-700 dark:text-gray-100',
        tableBodyCell: 'py-2 pr-3 text-gray-600 dark:text-gray-300',
        stackSm: 'mt-4 space-y-3',
        rowBetween: 'flex items-center justify-between',
        textStrong: 'text-sm font-medium text-gray-700 dark:text-gray-300',
        textDanger: 'text-sm font-medium theme-tone-danger',
        loadingCard: 'rounded-2xl border border-gray-200 bg-white p-4 md:p-6 text-center text-sm text-gray-600 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400',
    },
    profile: {
        loadingPage: 'app-page',
        page: 'app-page space-y-4',
        loadingText: 'text-slate-500 font-medium dark:text-gray-400',
        actionRow: 'flex items-center gap-2',
        themeToggle: 'inline-flex h-10 w-10 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-600 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700',
        cardStack: 'p-4 space-y-4',
        rowBetween: 'flex flex-wrap items-center justify-between gap-4',
        identityWrap: 'flex items-center gap-5',
        avatar: 'w-20 h-20 rounded-full overflow-hidden border border-gray-200 theme-status-info flex items-center justify-center text-sm font-medium dark:border-gray-600',
        avatarImage: 'w-full h-full object-cover',
        titleRow: 'text-sm font-medium text-gray-900 flex items-center gap-3 dark:text-gray-100',
        roleBadge: 'text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded-md self-start dark:bg-gray-700 dark:text-gray-300',
        planBadgeBase: 'text-xs px-2 py-0.5 rounded-md self-start',
        planFree: 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300',
        planPremium: 'theme-status-caution',
        planPro: 'theme-status-info',
        email: 'text-sm text-gray-600 dark:text-gray-400',
        statCard: 'bg-white border border-gray-200 rounded-2xl shadow-sm p-4 dark:bg-gray-800 dark:border-gray-700',
        statLabel: 'text-xs uppercase tracking-wide text-gray-400 dark:text-gray-500',
        statValue: 'mt-1 text-sm font-medium text-gray-900 wrap-break-word dark:text-gray-100',
        sectionHeading: 'space-y-1',
        sectionSubText: 'mt-1 text-sm text-gray-600 dark:text-gray-400',
        sectionStack: 'space-y-4',
        statGrid: 'grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3',
    },
    profileTemplate: {
        page: 'app-page space-y-4',
        shell: 'space-y-6 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800 md:p-6',
        header: 'flex flex-col gap-4 border-b border-gray-100 pb-4 dark:border-gray-700 md:flex-row md:items-start md:justify-between',
        identity: 'flex min-w-0 items-center gap-4',
        avatar: 'flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full border border-gray-200 theme-status-info text-sm font-medium dark:border-gray-700 md:h-20 md:w-20',
        avatarImage: 'h-full w-full object-cover',
        titleWrap: 'min-w-0 space-y-1',
        titleRow: 'flex flex-wrap items-center gap-2',
        title: 'text-lg font-semibold text-gray-900 dark:text-gray-100',
        email: 'text-sm text-gray-600 dark:text-gray-400',
        actions: 'flex flex-wrap items-center gap-2 md:justify-end',
        actionButton: 'inline-flex h-10 w-10 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-600 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700',
        body: 'space-y-4',
        section: 'space-y-4 rounded-2xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-900/50',
        sectionTitle: 'text-xs uppercase tracking-wide text-gray-400 dark:text-gray-500',
        sectionText: 'text-sm text-gray-600 dark:text-gray-400',
        sectionDivider: 'border-t border-gray-100 pt-4 dark:border-gray-700',
    },
    profileEdit: {
        page: 'app-page space-y-4',
        formShell: 'mx-auto rounded-2xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800',
        form: 'flex flex-col gap-4',
        section: 'space-y-4',
        sectionDivider: 'border-t border-gray-100 pt-4 dark:border-gray-700',
        sectionTitle: 'text-xs uppercase tracking-wide text-gray-400 dark:text-gray-500',
        previewStrip: 'flex items-center gap-4 rounded-xl border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/50',
        previewAvatar: 'flex h-16 w-16 items-center justify-center overflow-hidden rounded-full border border-gray-200 theme-status-info text-sm font-medium dark:border-gray-700',
        previewImage: 'h-full w-full object-cover',
        previewTitle: 'text-sm font-medium text-gray-900 dark:text-gray-100',
        previewText: 'text-sm text-gray-600 dark:text-gray-400',
        grid: 'grid grid-cols-1 gap-4 md:grid-cols-2',
        field: 'flex flex-col gap-2',
        fieldWide: 'flex flex-col gap-2 md:col-span-2',
        label: 'text-xs uppercase tracking-wide text-gray-400 dark:text-gray-500',
        input: 'w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-[var(--qb-primary)] dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder:text-gray-500',
        inputReadonly: 'bg-gray-50 text-gray-500 dark:bg-gray-800 dark:text-gray-400',
        inputError: 'border-red-300 focus:ring-red-400 dark:border-red-500 dark:focus:ring-red-400',
        errorText: 'text-xs font-medium text-red-600 dark:text-red-400',
        noteText: 'text-sm text-gray-600 dark:text-gray-400',
        footer: 'sticky bottom-0 z-20 -mx-4 mt-4 flex items-center justify-between gap-3 border-t border-gray-100 bg-white/95 px-4 py-3 backdrop-blur md:static md:mx-0 md:border-t-0 md:bg-transparent md:px-0 md:py-0 dark:border-gray-700 dark:bg-gray-800/95 md:dark:bg-transparent',
    },
    studio: {
        pageShell: 'app-page animate-in fade-in duration-500',
        controlBar: 'w-full theme-radius-card border theme-border theme-surface p-3 shadow-sm theme-interactive',
        controlInner: 'flex flex-col items-stretch gap-3 lg:flex-row lg:items-center lg:justify-between',
        searchWrap: 'w-full lg:flex-1',
        segmentedShell: 'inline-flex items-center gap-1 rounded-xl border theme-border theme-surface-soft px-1 py-1',
        segmentedInner: 'inline-flex items-center rounded-lg bg-transparent p-0.5',
        modeBtnBase: 'inline-flex h-8 items-center gap-1.5 rounded-md px-2.5 text-sm font-medium transition-all',
        modeBtnActive: 'theme-surface theme-text-primary shadow-sm',
        modeBtnIdle: 'theme-text-muted hover:theme-text-primary',
        modeBtnDisabled: 'disabled:cursor-not-allowed disabled:opacity-50',
        sortFilterLabel: 'inline-flex h-8 items-center gap-1.5 rounded-lg border theme-border theme-surface px-2.5 text-sm font-medium theme-text-secondary theme-interactive theme-hover-surface',
        sortFilterSelect: 'bg-transparent text-sm font-medium theme-text-primary outline-none',
        actionWrap: 'flex w-full items-center justify-between gap-2 lg:w-auto lg:justify-end',
        controlsRow: 'hidden items-center gap-2 md:flex',
        mobileControlsWrap: 'relative md:hidden',
        mobileControlsTrigger: 'inline-flex h-9 items-center gap-1.5 rounded-xl border theme-border theme-surface px-3 text-sm font-medium theme-text-secondary theme-interactive theme-hover-surface',
        mobileControlsMenu: 'absolute left-0 top-11 z-60 w-[min(20rem,calc(100vw-2rem))] space-y-2 theme-radius-card border theme-border theme-surface p-2 shadow-lg',
        mobileControlsOverlay: 'fixed inset-0 z-50 md:hidden',
        mobileControlsSection: 'grid gap-2',
        searchInput: 'h-9 w-full max-w-md rounded-xl border theme-border theme-surface px-3.5 py-2 text-sm theme-text-primary outline-none transition-all placeholder:theme-text-muted focus:border-[var(--qb-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--qb-primary)_22%,white)] sm:px-4',
        newBtn: 'inline-flex h-9 items-center gap-2 rounded-xl bg-(--qb-primary) px-3.5 text-sm font-medium text-white shadow-sm theme-interactive hover:bg-[var(--qb-primary-strong)] sm:px-4',
    },
    host: {
        loading: 'min-h-screen bg-[linear-gradient(180deg,var(--qb-surface-1)_0%,var(--qb-surface-2)_100%)] flex flex-col items-center justify-center theme-text-muted',
        header: 'sticky top-0 z-30 min-h-18 border-b theme-border theme-surface/85 backdrop-blur-xl flex items-center justify-between gap-3 px-4 py-3 shadow-sm shrink-0 md:px-6',
        headerLeft: 'flex min-w-0 items-center gap-3 md:gap-4',
        titleClamp: 'max-w-72 truncate text-lg font-black leading-tight tracking-tight text-[var(--qb-text-1)] md:max-w-104 md:text-xl xl:max-w-136 xl:text-2xl',
        headerEyebrow: 'text-[10px] font-black uppercase tracking-[0.28em] theme-text-muted',
        headerMetaRow: 'mt-1 flex items-center gap-2',
        headerMetaChip: 'inline-flex items-center rounded-full border theme-border theme-surface-soft px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] theme-text-secondary',
        headerMetaChipAccent: 'inline-flex items-center rounded-full border border-[color-mix(in_srgb,var(--qb-primary)_28%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-primary)_12%,var(--qb-surface-1))] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-[var(--qb-primary)]',
        navBack: 'theme-surface border theme-border theme-text-secondary hover:theme-surface-soft hover:theme-text-primary focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)]',
        headerActions: 'hidden items-center gap-3 xl:flex',
        headerActionsMobile: 'flex items-center gap-2 xl:hidden',
        tabShell: 'inline-flex rounded-2xl border theme-border theme-surface-soft p-1 shadow-inner',
        tabActive: 'rounded-xl text-xs px-5 py-2 shadow-sm',
        tabBtn: 'rounded-xl px-5 py-2 text-sm font-semibold theme-text-secondary hover:theme-text-primary transition-colors',
        tabBtnWithIcon: 'rounded-xl px-5 py-2 text-sm font-semibold theme-text-secondary hover:theme-text-primary transition-colors inline-flex items-center gap-1.5',
        saveBtn: 'inline-flex h-10 w-28 shrink-0 items-center justify-center gap-2 rounded-xl px-4 py-2 text-xs font-semibold shadow-sm transition-colors',
        launchBtn: 'inline-flex items-center gap-2 px-6 py-2.5 text-xs rounded-xl shadow-sm transition-all',
        mobileMenuWrap: 'relative xl:hidden',
        mobileMenuPanel: 'absolute right-0 top-11 z-40 w-64 rounded-[1.5rem] border theme-border theme-surface/95 p-2 shadow-2xl backdrop-blur-xl',
        mobileMenuItem: 'flex w-full items-center gap-2 rounded-xl px-3 py-3 text-left text-sm font-semibold theme-text-secondary hover:theme-surface-soft hover:theme-text-primary',
        mobileMenuDivider: 'mx-2 my-2 border-t theme-border',
        errorWrap: 'app-page fixed top-17 left-2 right-2 z-60',
        importShell: 'oe-import-shell',
        aiPromptHeader: 'flex items-center justify-between gap-3',
        aiPromptCopyBtn: 'rounded-xl px-4 py-2 text-sm font-semibold text-[var(--qb-primary)] hover:theme-surface-soft',
        aiPromptCode: 'mt-4 max-h-56 overflow-auto whitespace-pre-wrap rounded-2xl border theme-border theme-surface p-4 text-sm theme-text-secondary',
        spin: 'animate-spin',
        aiSkeleton: 'h-20 animate-pulse rounded-xl border theme-border theme-surface-soft',
        aiQuestionHeader: 'flex items-center justify-between gap-2',
        aiQuestionCardPad: 'p-4',
        aiQuestionDifficulty: 'rounded-full theme-surface-soft px-2 py-1 text-[10px] font-black uppercase tracking-widest theme-text-secondary',
        aiOptionGrid: 'mt-3 grid grid-cols-1 gap-2 md:grid-cols-2',
        aiOptionBase: 'rounded-lg border px-3 py-2 text-sm font-semibold',
        aiOptionCorrect: 'border-emerald-300 bg-emerald-50 text-emerald-700',
        aiOptionWrong: 'border theme-border theme-surface-soft theme-text-secondary',
        aiExplainMargin: 'mt-3',
        aiExplainLabel: 'font-bold uppercase tracking-widest',
        aiGenerateBtn: 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold shadow-sm disabled:cursor-not-allowed disabled:opacity-60',
        aiActionBtn: 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-60',
        editorRoot: 'fixed inset-0 z-50 flex flex-col overflow-y-auto overflow-x-hidden bg-[var(--qb-surface-1)] theme-text-primary md:overflow-hidden [--qb-editor-mobile-surface:rgba(248,250,252,0.96)] [--qb-editor-mobile-border:rgba(148,163,184,0.3)] [--qb-editor-panel:rgba(255,255,255,0.82)] [--qb-editor-panel-soft:rgba(255,255,255,0.64)] [--qb-editor-panel-border:rgba(148,163,184,0.24)] [--qb-editor-option-bg:rgba(255,255,255,0.72)] [--qb-editor-option-border:rgba(148,163,184,0.24)] [--qb-editor-option-hover:rgba(255,255,255,0.92)] [--qb-editor-option-letter-bg:rgba(248,250,252,0.9)] [--qb-editor-option-letter-border:rgba(148,163,184,0.26)] [--qb-editor-toggle-track-off:rgba(148,163,184,0.3)] [--qb-editor-toggle-track-success:rgba(79,70,229,0.45)] [--qb-editor-toggle-track-warning:rgba(245,158,11,0.45)] [--qb-editor-toggle-on-success-bg:rgba(79,70,229,0.12)] [--qb-editor-toggle-on-success-border:rgba(79,70,229,0.3)] [--qb-editor-toggle-on-warning-bg:rgba(245,158,11,0.12)] [--qb-editor-toggle-on-warning-border:rgba(245,158,11,0.3)] [--qb-editor-toggle-thumb:#ffffff] [--qb-editor-correct-bg:rgba(34,197,94,0.12)] [--qb-editor-correct-border:rgba(34,197,94,0.4)] [--qb-editor-correct-text:#15803d] dark:[--qb-editor-mobile-surface:rgba(20,20,30,0.95)] dark:[--qb-editor-mobile-border:rgba(255,255,255,0.08)] dark:[--qb-editor-panel:rgba(255,255,255,0.03)] dark:[--qb-editor-panel-soft:rgba(255,255,255,0.04)] dark:[--qb-editor-panel-border:rgba(255,255,255,0.1)] dark:[--qb-editor-option-bg:rgba(255,255,255,0.04)] dark:[--qb-editor-option-border:rgba(255,255,255,0.08)] dark:[--qb-editor-option-hover:rgba(255,255,255,0.06)] dark:[--qb-editor-option-letter-bg:rgba(255,255,255,0.04)] dark:[--qb-editor-option-letter-border:rgba(255,255,255,0.12)] dark:[--qb-editor-toggle-track-off:rgba(255,255,255,0.12)] dark:[--qb-editor-toggle-track-success:rgba(99,102,241,0.5)] dark:[--qb-editor-toggle-track-warning:rgba(245,158,11,0.5)] dark:[--qb-editor-toggle-on-success-bg:rgba(34,197,94,0.1)] dark:[--qb-editor-toggle-on-success-border:rgba(34,197,94,0.3)] dark:[--qb-editor-toggle-on-warning-bg:rgba(245,158,11,0.1)] dark:[--qb-editor-toggle-on-warning-border:rgba(245,158,11,0.3)] dark:[--qb-editor-toggle-thumb:#ffffff] dark:[--qb-editor-correct-bg:rgba(34,197,94,0.08)] dark:[--qb-editor-correct-border:rgba(34,197,94,0.45)] dark:[--qb-editor-correct-text:rgba(134,239,172,1)]',
        editorBody: 'grid flex-1 min-h-0 grid-cols-1 gap-2 overflow-hidden p-2 md:grid-cols-[240px_minmax(0,1fr)] md:p-3 xl:grid-cols-[280px_minmax(0,1fr)_340px] xl:gap-3 xl:p-3',
        // Mobile Layout: Canvas-first + Bottom Drawer
        mobileShellContainer: 'md:hidden flex flex-col h-screen overflow-hidden',
        mobileHeader: 'flex items-center justify-between gap-2 border-b px-3 py-3 backdrop-blur-sm border-[var(--qb-editor-mobile-border)] bg-[var(--qb-editor-mobile-surface)]',
        mobileHeaderTitle: 'text-base font-bold text-[var(--qb-text-1)]',
        mobileHeaderMeta: 'text-xs font-semibold theme-text-muted',
        mobileCanvasWrapper: 'flex-1 overflow-y-auto p-2 pb-20',
        mobileBottomNav: 'fixed bottom-0 left-0 right-0 flex items-center justify-between gap-1 border-t p-2 backdrop-blur-sm md:hidden border-[var(--qb-editor-mobile-border)] bg-[var(--qb-editor-mobile-surface)]',
        mobileNavBtn: 'flex-1 flex items-center justify-center gap-2 rounded-lg px-2 py-2.5 text-xs font-semibold theme-text-secondary transition-colors hover:bg-[var(--qb-editor-panel-soft)]',
        mobileNavBtnActive: 'border theme-text-primary border-[color-mix(in_srgb,var(--qb-primary)_34%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-primary)_16%,var(--qb-surface-1))]',
        mobileDrawer: 'fixed bottom-16 left-0 right-0 max-h-[60vh] overflow-y-auto rounded-t-3xl border-t p-3 backdrop-blur-sm md:hidden border-[var(--qb-editor-mobile-border)] bg-[var(--qb-editor-mobile-surface)]',
        // Legacy Mobile Tokens (kept for compatibility)
        mobileShell: 'flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto p-2 pb-6 md:hidden',
        mobileHero: 'space-y-3 rounded-2xl border theme-border theme-surface p-4',
        mobileHeroTop: 'flex items-start justify-between gap-4',
        mobileHeroTitle: 'min-w-0 space-y-1',
        mobileHeroEyebrow: 'text-[10px] font-black uppercase tracking-[0.28em] theme-text-muted',
        mobileHeroName: 'truncate text-xl font-black leading-tight tracking-tight text-[var(--qb-text-1)]',
        mobileHeroMeta: 'flex flex-wrap items-center gap-2',
        mobileHeroChip: 'inline-flex items-center rounded-full border theme-border theme-surface-soft px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] theme-text-secondary',
        mobileHeroChipAccent: 'inline-flex items-center rounded-full border border-[color-mix(in_srgb,var(--qb-primary)_28%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-primary)_12%,var(--qb-surface-1))] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-[var(--qb-primary)]',
        mobileHeroStats: 'grid grid-cols-3 gap-2 pt-1',
        mobileHeroStat: 'rounded-lg border theme-border theme-surface-soft p-3 text-center',
        mobileHeroStatLabel: 'text-[10px] font-black uppercase tracking-[0.18em] theme-text-muted',
        mobileHeroStatValue: 'mt-1 text-sm font-black text-[var(--qb-text-1)]',
        mobileHeroStatAccent: 'mt-1 text-sm font-black text-[var(--qb-primary)]',
        mobileTabBar: 'grid grid-cols-2 gap-2 rounded-xl border theme-border theme-surface-soft p-1',
        mobileTabBtn: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold theme-text-secondary transition-colors',
        mobileTabBtnActive: 'theme-surface theme-text-primary',
        mobileTabPanel: 'min-h-0 space-y-2 rounded-xl border theme-border theme-surface-soft p-3',
        mobileTabPanelHeader: 'flex items-center justify-between gap-3 px-1 pt-1',
        mobileTabPanelTitle: 'text-xs font-black uppercase tracking-[0.22em] theme-text-muted',
        mobileTabPanelBody: 'min-h-0 space-y-3',
        mobilePanelShell: 'min-h-0 space-y-3',
        slideAside: 'hidden min-h-0 flex-col overflow-hidden rounded-2xl border theme-border theme-surface/95 focus-visible:ring-2 focus-visible:ring-(--qb-primary) md:flex md:overflow-y-auto',
        slideTopPad: 'border-b theme-border p-3 space-y-2',
        slideAddBtn: 'w-full inline-flex items-center justify-center gap-2 rounded-xl bg-(--qb-primary) px-3 py-2 text-xs font-bold uppercase tracking-wide text-white transition-transform hover:scale-[1.01] hover:bg-[var(--qb-primary-strong)]',
        slideListWrap: 'flex-1 overflow-y-auto px-2 pb-8 pt-1.5 space-y-1.5',
        slideItem: 'group flex w-full flex-col gap-2 text-left focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)]',
        slideItemShell: 'relative overflow-hidden rounded-lg p-1 transition-all duration-150',
        slideItemShellActive: 'bg-[color-mix(in_srgb,var(--qb-primary)_10%,var(--qb-surface-1))] shadow-[0_0_0_1px_color-mix(in_srgb,var(--qb-primary)_30%,transparent)]',
        slideItemRow: 'group/slide flex items-center gap-2 rounded-lg px-1 py-1.5 transition-colors hover:theme-surface-soft',
        slideSelectBtn: 'flex min-w-0 flex-1 items-center gap-2 text-left',
        slideIndex: 'w-7 shrink-0 text-right text-xs font-semibold theme-text-muted',
        slideThumb: 'relative flex-1 min-w-0 h-[5.25rem] overflow-hidden rounded-md border p-2.5 flex flex-col justify-between transition-all',
        slideThumbActive: 'border-2 border-(--qb-primary) bg-[color-mix(in_srgb,var(--qb-primary)_12%,var(--qb-surface-1))] shadow-sm',
        slideThumbIdle: 'border theme-border theme-surface-soft group-hover/slide:theme-surface',
        slideThumbPreview: 'space-y-1',
        slideThumbTitle: 'line-clamp-1 text-[10px] font-semibold theme-text-primary',
        slideThumbMeta: 'text-[9px] font-semibold uppercase tracking-[0.12em] theme-text-muted',
        slideThumbAccent: 'hidden',
        slideBarStrong: 'w-full h-1 bg-[var(--qb-text-3)] rounded-full',
        slideBarSoft: 'w-2/3 h-1 bg-[color-mix(in_srgb,var(--qb-text-3)_70%,white)] rounded-full',
        slideMiniGrid: 'grid grid-cols-2 gap-1 w-full mt-1',
        slideMiniCell: 'h-0.5 rounded-full bg-[color-mix(in_srgb,var(--qb-text-2)_38%,white)]',
        slideActionRail: 'flex items-center gap-1 opacity-100 md:opacity-0 md:group-hover/slide:opacity-100 transition-opacity',
        slideActionBase: 'inline-flex h-6 w-6 items-center justify-center rounded-md border theme-border theme-surface text-[10px] theme-text-muted transition-colors focus-ring',
        slideActionTop: 'hover:text-gray-800 hover:bg-white',
        slideActionMid: 'hover:text-red-700 hover:bg-red-50',
        slideActionBottom: 'hover:text-gray-800 hover:bg-white',
        slideEmptyState: 'rounded-lg border border-dashed theme-border px-3 py-4 text-center text-xs theme-text-muted',
        slideDragGhost: 'scale-[1.02] opacity-70 shadow-xl',
        slideDropTarget: 'ring-2 ring-(--qb-primary)',
        configAside: 'hidden min-h-0 flex-col overflow-hidden rounded-2xl border theme-border theme-surface xl:flex xl:overflow-y-auto',
        configHeader: 'border-b theme-border px-4 py-4 xl:px-6 space-y-2',
        configSection: 'flex-1 space-y-4 p-3 xl:p-4 overflow-y-auto',
        configFieldGroupTop: 'space-y-4 border-b theme-border pb-4',
        configTitle: 'pl-1 text-xs font-bold uppercase tracking-wider theme-text-muted',
        configSubtitle: 'text-sm font-semibold theme-text-primary',
        configDescription: 'text-xs leading-4 theme-text-muted',
        configStack: 'space-y-3',
        configAccordion: 'overflow-hidden rounded-lg border theme-border theme-surface-soft',
        configAccordionHeader: 'flex min-h-11 w-full items-center justify-between gap-3 px-4 py-3 text-left',
        configAccordionTitle: 'text-sm font-semibold theme-text-primary',
        configAccordionChevron: 'theme-text-muted transition-transform',
        configAccordionBody: 'border-t theme-border px-4 py-4 space-y-4',
        configToggleShell: 'rounded-xl border p-1 transition-colors',
        configToggleShellSuccess: 'border-[color-mix(in_srgb,var(--qb-primary)_36%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-primary)_14%,var(--qb-surface-1))]',
        configToggleShellWarning: 'border-[color-mix(in_srgb,var(--qb-accent)_34%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-accent)_14%,var(--qb-surface-1))]',
        configToggleBtn: 'w-full flex items-center justify-between gap-4 px-4 py-3 rounded-lg border theme-border theme-surface transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:theme-surface-soft',
        configToggleOnSuccess: 'text-[var(--qb-text-1)] border-[var(--qb-editor-toggle-on-success-border)] bg-[var(--qb-editor-toggle-on-success-bg)]',
        configToggleOnWarning: 'text-[var(--qb-text-1)] border-[var(--qb-editor-toggle-on-warning-border)] bg-[var(--qb-editor-toggle-on-warning-bg)]',
        configToggleOff: 'theme-text-secondary',
        configToggleLabel: 'text-[11px] font-bold uppercase tracking-[0.15em]',
        configSwitchTrack: 'relative inline-flex h-5 w-10 items-center rounded-full transition-colors bg-[var(--qb-editor-toggle-track-off)]',
        configSwitchTrackOnSuccess: 'bg-[var(--qb-editor-toggle-track-success)]',
        configSwitchTrackOnWarning: 'bg-[var(--qb-editor-toggle-track-warning)]',
        configSwitchTrackOff: 'bg-[var(--qb-editor-toggle-track-off)]',
        configSwitchThumb: 'inline-block h-3.5 w-3.5 transform rounded-full transition-transform bg-[var(--qb-editor-toggle-thumb)]',
        configSwitchThumbOn: 'translate-x-5',
        configSwitchThumbOff: 'translate-x-1',
        configHint: 'px-1',
        configField: 'space-y-2',
        configFieldLabel: 'mb-2 block text-[11px] font-bold uppercase tracking-[0.12em] theme-text-muted',
        configFieldSelect: 'w-full rounded-xl border theme-border theme-surface px-3 py-2 text-sm theme-text-primary outline-none transition-colors focus:border-[color-mix(in_srgb,var(--qb-primary)_42%,var(--qb-border))] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--qb-primary)_24%,transparent)]',
        configSelectNative: 'appearance-none pr-10',
        configApplyBtn: 'w-full justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed',
        configDividerTop: 'border-t theme-border pt-6 space-y-4',
        configSelectWrap: 'relative',
        configSelectIconWrap: 'absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50',
        iconAccent: 'fill-[var(--qb-primary)] text-[var(--qb-primary)]',
        configFooter: 'mt-auto border-t theme-border p-4 xl:p-6',
        configFooterNote: 'mb-3 text-xs font-medium theme-text-muted',
        configDeleteBtn: 'w-full justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold',
        configToggleCard: 'space-y-2 rounded-lg border theme-border theme-surface-soft p-3 transition-all',
        configToggleCardTitle: 'text-sm font-semibold theme-text-primary',
        configToggleCardBody: 'text-xs leading-5 theme-text-muted',
        canvasMain: 'flex min-h-0 flex-1 flex-col items-center overflow-y-auto px-0 py-0 md:px-0 md:py-0',
        canvasCard: 'relative flex w-full min-h-[24rem] max-w-none flex-col rounded-2xl border px-4 py-4 md:px-6 md:py-6 xl:aspect-video xl:max-w-5xl xl:px-10 xl:py-8 border-[var(--qb-editor-panel-border)] bg-[var(--qb-editor-panel)]',
        canvasHeader: 'mb-4 flex items-center justify-between md:mb-6',
        canvasHeaderLeft: 'flex items-center gap-2',
        canvasSlidePill: 'inline-flex items-center px-3 py-1.5 rounded-lg bg-[color-mix(in_srgb,var(--qb-primary)_14%,var(--qb-surface-1))] text-[var(--qb-primary)] text-xs font-bold uppercase tracking-widest',
        canvasHeaderIcon: 'opacity-10',
        canvasContent: 'flex flex-col flex-1',
        canvasRow: 'flex flex-col gap-5 flex-1 lg:flex-row lg:items-start lg:gap-8',
        canvasBadgeCol: 'mt-1 min-w-12 h-fit',
        canvasBadge: 'flex items-center justify-center w-12 h-12 rounded-lg bg-[var(--qb-primary)] text-white font-black text-lg',
        canvasQuestionCol: 'flex max-w-3xl flex-1 flex-col gap-4 rounded-lg p-4 md:p-5 bg-[var(--qb-editor-panel-soft)]',
        canvasQuestionMeta: 'inline-flex items-center gap-2 self-start rounded-full border theme-border theme-surface-soft px-3 py-1 text-[11px] font-bold uppercase tracking-[0.2em] theme-text-secondary',
        canvasQuestionInput: 'w-full bg-transparent resize-none text-lg md:text-xl xl:text-2xl font-semibold theme-text-primary placeholder:theme-text-muted leading-snug text-left border-none outline-none focus:outline-none focus:ring-0 focus-visible:outline-none focus-visible:ring-0',
        canvasOptionsGrid: 'grid grid-cols-1 gap-2 w-full md:grid-cols-2 md:gap-3',
        canvasOptionCard: 'relative group transition-all duration-200 hover:-translate-y-0.5',
        canvasOptionButton: 'flex w-full min-h-11 cursor-text items-center gap-3 overflow-hidden rounded-lg border px-3 text-left text-sm font-semibold transition-all duration-200 md:min-h-24 md:px-4 border-[var(--qb-editor-option-border)] bg-[var(--qb-editor-option-bg)] hover:bg-[var(--qb-editor-option-hover)] focus-within:border-[var(--qb-primary)]',
        canvasOptionButtonCorrect: 'border-[var(--qb-editor-correct-border)] bg-[var(--qb-editor-correct-bg)]',
        canvasOptionButtonIdle: 'hover:border-[color-mix(in_srgb,var(--qb-primary)_30%,var(--qb-editor-option-border))]',
        canvasOptionLetter: 'flex h-8 w-8 shrink-0 items-center justify-center rounded-md border text-xs font-black uppercase tracking-[0.18em] theme-text-secondary border-[var(--qb-editor-option-letter-border)] bg-[var(--qb-editor-option-letter-bg)]',
        canvasOptionLetterCorrect: 'border-[var(--qb-editor-correct-border)] bg-[var(--qb-editor-correct-bg)] text-[var(--qb-editor-correct-text)]',
        canvasOptionContent: 'flex min-w-0 flex-1 items-center gap-2',
        canvasOptionState: 'text-[10px] font-black uppercase tracking-[0.22em] text-[var(--qb-editor-correct-text)]',
        canvasOptionInput: 'w-full min-w-0 bg-transparent border-none theme-text-primary placeholder:theme-text-muted outline-none focus:outline-none focus:ring-0 focus-visible:outline-none focus-visible:ring-0',
        canvasEmpty: 'flex flex-col items-center justify-center flex-1 text-center theme-text-muted space-y-4 py-8',
        canvasEmptyText: 'text-base md:text-lg font-semibold',
        canvasEmptySub: 'text-sm theme-text-muted',
        canvasFooter: 'mt-4 text-[10px] tracking-widest uppercase theme-text-muted md:mt-6',
        saveStateBadge: 'pointer-events-none fixed bottom-4 right-4 z-60 hidden rounded-xl border theme-border theme-surface/90 px-3 py-2 text-xs font-semibold theme-text-secondary backdrop-blur lg:block',
    },
    pagination: {
        wrapper: 'mt-8 flex flex-col items-center justify-between gap-4 border-t theme-border pt-6 sm:flex-row',
        info: 'text-sm theme-text-secondary',
        infoStrong: 'font-semibold theme-text-primary',
        nav: 'inline-flex items-center -space-x-px rounded-xl shadow-sm',
        btn: 'inline-flex items-center justify-center px-4 py-2 text-sm font-medium transition-all duration-200 focus:z-10 focus:outline-none focus:ring-2 focus:ring-[var(--qb-primary)]',
        btnActive: 'bg-[var(--qb-primary)] text-white hover:bg-[var(--qb-primary-strong)]',
        btnIdle: 'theme-surface theme-text-secondary border theme-border hover:theme-surface-soft hover:theme-text-primary',
        btnDisabled: 'theme-surface-soft theme-text-muted cursor-not-allowed border theme-border',
        btnFirst: 'rounded-l-xl',
        btnLast: 'rounded-r-xl',
        select: 'rounded-lg border theme-border theme-surface px-3 py-1.5 text-sm theme-text-secondary outline-none focus:border-[var(--qb-primary)] focus:ring-1 focus:ring-[var(--qb-primary)]',
    },
    home: {
        page: 'relative overflow-hidden',
        glowWrap: 'absolute inset-0 -z-10',
        glowOrb: 'absolute left-1/2 top-[-10%] h-[40rem] w-[40rem] -translate-x-1/2 rounded-full bg-[color-mix(in_srgb,var(--qb-primary)_15%,transparent)] blur-[100px] pointer-events-none',
    },
};
