export const layoutStyles = {
    dashboardHeader: 'flex flex-col items-start justify-between gap-4 md:flex-row md:items-center',
    sectionSurface: 'rounded-2xl border border-gray-200 bg-white p-4 md:p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800',
    pageStack: 'space-y-6',
    cardList: 'space-y-2',
    cardGrid: 'space-y-3 md:grid md:grid-cols-2 md:gap-5 md:space-y-0 xl:grid-cols-3 2xl:grid-cols-4',
    twoColXl: 'grid grid-cols-1 gap-6 xl:grid-cols-2',
    subHeader: 'mb-6 flex flex-col gap-6 md:flex-row md:items-center md:justify-between',
    subHeaderInfo: 'min-w-0 space-y-1',
    subHeaderActions: 'flex w-full flex-wrap items-center gap-3 md:w-auto md:justify-end',
};

export const modalStyles = {
    overlay: 'fixed inset-0 z-[var(--z-modal)] bg-slate-900/40 backdrop-blur-sm',
    overlayLight: 'fixed inset-0 z-40 bg-black/20 backdrop-blur-sm',
    overlayCenterPad: 'fixed inset-0 z-100 flex items-center justify-center p-6',
    overlayTop: 'fixed inset-0 z-[9999] flex items-center justify-center bg-slate-900/40 p-6 backdrop-blur-sm',
    dialog: 'mx-4 w-full max-w-md overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-2xl dark:border-gray-700 dark:bg-gray-800',
    shellCenter: 'fixed left-1/2 top-1/2 z-50 w-full max-w-md -translate-x-1/2 -translate-y-1/2',
    shellPanel: 'rounded-[2rem] border border-gray-100 bg-white/95 p-8 shadow-2xl backdrop-blur-lg animate-in fade-in scale-95 duration-200 dark:border-gray-700 dark:bg-gray-800/95',
    panelWide: 'w-full max-w-2xl max-h-[80vh] overflow-hidden rounded-4xl border border-gray-100 bg-white shadow-2xl animate-in zoom-in duration-300 dark:border-gray-700 dark:bg-gray-800',
    panelXl: 'w-full max-w-5xl overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-2xl dark:border-gray-700 dark:bg-gray-800',
    headerRow: 'flex items-start justify-between gap-4 border-b border-gray-100 p-6 dark:border-gray-700',
    headerRowSoft: 'flex items-center justify-between border-b border-gray-100 bg-gray-50 p-10 dark:border-gray-700 dark:bg-gray-800',
    contentScroll: 'flex-1 overflow-y-auto p-8 space-y-3',
    contentSection: 'space-y-4 p-6',
    contentSectionScroll: 'max-h-[52vh] space-y-4 overflow-y-auto p-6',
    formGrid: 'grid grid-cols-1 gap-5 border-b border-gray-100 p-6 lg:grid-cols-4 dark:border-gray-700',
    formGridWide: 'lg:col-span-2',
    stackSm: 'space-y-2',
    stackMd: 'space-y-3',
    body: 'flex items-start gap-4 p-6 pb-4',
    footer: 'flex gap-3 border-t border-gray-100 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800',
    footerRight: 'flex flex-col gap-3 border-t border-gray-100 bg-gray-50 p-4 sm:flex-row sm:justify-end dark:border-gray-700 dark:bg-gray-800',
    closeButton: 'rounded-xl p-2 text-slate-400 transition-colors hover:bg-gray-100 hover:text-slate-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-100',
    closeButtonSoft: 'rounded-2xl border border-gray-100 bg-white p-4 text-slate-600 transition-all hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700',
    tabs: 'inline-flex rounded-xl border border-gray-200 p-1 dark:border-gray-700',
    tabBtn: 'rounded-lg px-3 py-1 text-xs font-black uppercase tracking-widest',
    textarea: 'min-h-[260px] w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100',
    headingHero: 'max-w-100 truncate text-4xl font-black uppercase text-slate-900 dark:text-gray-100',
};
