export const navbar = {
    container: 'relative sticky top-0 z-[var(--z-nav)] h-14 border-b theme-border theme-surface',
    inner: 'mx-auto flex h-14 w-full max-w-7xl items-center justify-between px-6',
    brandLink: 'flex items-center gap-3',
    brandTitle: 'text-4xl font-semibold tracking-tight theme-text-primary',
    brandAccent: 'theme-primary',
    navLink: 'text-xs sm:text-sm font-medium theme-text-secondary hover:theme-text-primary',
    navLinkActive: 'text-xs sm:text-sm font-semibold theme-text-primary',
    menu: 'hidden items-center gap-6 ml-10 lg:flex',
    actions: 'hidden items-center gap-3 lg:flex',
    center: 'hidden flex-1 lg:block',
    mobileActions: 'flex items-center gap-2 lg:hidden',
    mobileToolbarButton: 'inline-flex h-10 w-10 items-center justify-center rounded-full theme-text-secondary transition-colors hover:theme-surface-soft hover:theme-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    mobileMenuButton: 'inline-flex h-10 w-10 items-center justify-center rounded-full theme-text-secondary transition-colors hover:theme-surface-soft hover:theme-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    mobileBackdrop: 'fixed inset-0 top-14 z-40 bg-slate-950/20 backdrop-blur-[1px] lg:hidden',
    mobilePanel: 'fixed inset-x-0 top-14 z-50 flex h-[calc(100dvh-3.5rem)] flex-col overflow-y-auto border-b theme-border bg-[color-mix(in_srgb,var(--qb-surface-1)_88%,transparent)] px-4 backdrop-blur-2xl shadow-[0_24px_80px_rgba(15,23,42,0.14)] lg:hidden',
    mobilePanelOpen: 'translate-y-0 pb-6 pt-4 opacity-100 pointer-events-auto',
    mobilePanelClosed: '-translate-y-3 pb-0 pt-0 opacity-0 pointer-events-none',
    mobileBadgeRow: 'flex items-center justify-between gap-3',
    mobileHint: 'text-xs font-medium uppercase tracking-[0.18em] theme-text-muted',
    mobileMenu: 'mt-4 grid gap-2',
    mobileBottomSpacer: 'flex-1 min-h-6',
    mobileSectionTitle: 'mt-5 mb-2 text-xs font-semibold uppercase tracking-[0.14em] theme-text-muted',
    mobileNavLink: 'flex items-center justify-between rounded-2xl border theme-border px-4 py-3 text-sm font-medium tracking-tight theme-text-secondary transition-colors hover:bg-[color-mix(in_srgb,var(--qb-primary)_12%,var(--qb-surface-1))] hover:text-[var(--qb-primary)]',
    mobileNavLinkActive: 'flex items-center justify-between rounded-2xl border border-[color-mix(in_srgb,var(--qb-primary)_42%,var(--qb-border))] bg-[color-mix(in_srgb,var(--qb-primary)_16%,var(--qb-surface-1))] px-4 py-3 text-sm font-semibold tracking-tight text-[var(--qb-primary)]',
    mobileCtaGroup: 'mt-4 grid gap-2 pb-2',
    mobilePrimaryButton: 'inline-flex min-h-11 items-center justify-center rounded-2xl bg-[var(--qb-primary)] px-4 py-3 text-sm font-medium tracking-tight text-white transition-colors hover:bg-[var(--qb-primary-strong)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    mobileSecondaryButton: 'inline-flex min-h-11 items-center justify-center rounded-2xl border theme-border px-4 py-3 text-sm font-medium tracking-tight theme-text-secondary transition-colors hover:theme-surface-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    mobileLogoutButton: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl border border-[color-mix(in_srgb,var(--qb-danger-ink)_30%,var(--qb-border))] px-4 py-3 text-sm font-medium tracking-tight theme-tone-danger transition-colors hover:bg-[var(--qb-danger-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-danger-ink)] focus-visible:ring-offset-2',
    primaryButton: 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium bg-[var(--qb-primary)] text-white transition-colors hover:bg-[var(--qb-primary-strong)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    secondaryButton: 'inline-flex items-center justify-center rounded-lg border theme-border px-4 py-2 text-sm font-medium theme-text-secondary transition-colors hover:theme-surface-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    badge: 'text-xs px-2.5 py-1 rounded-full font-medium inline-flex items-center gap-1.5',
    badgeDot: 'h-1.5 w-1.5 rounded-full bg-current',
    iconButton: 'inline-flex h-9 w-9 items-center justify-center rounded-full theme-text-secondary transition-colors hover:theme-surface-soft hover:theme-text-primary',
    profileMenuWrap: 'relative',
    avatarTrigger: 'inline-flex h-9 items-center gap-1 rounded-full border theme-border theme-surface pr-1 theme-text-secondary transition-colors hover:theme-surface-soft hover:theme-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    avatarCaret: 'theme-text-muted',
    avatar: 'h-9 w-9 overflow-hidden rounded-full border theme-border bg-[color-mix(in_srgb,var(--qb-primary)_14%,var(--qb-surface-1))] flex items-center justify-center text-sm font-medium text-[var(--qb-primary)]',
    avatarImage: 'h-full w-full object-cover',
    dropdown: 'absolute right-0 top-full mt-2 z-[100] min-w-56 rounded-xl border theme-border theme-surface p-1 shadow-xl',
    dropdownItem: 'flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium theme-text-secondary transition-colors hover:theme-surface-soft hover:theme-text-primary',
    dropdownDanger: 'text-[var(--qb-danger-ink)] hover:bg-[var(--qb-danger-soft)]',
};
