export const navbar = {
    container: 'relative sticky top-0 z-[var(--z-nav)] h-14 border-b border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900',
    inner: 'mx-auto flex h-14 w-full max-w-7xl items-center justify-between px-6',
    brandLink: 'flex items-center gap-3',
    brandTitle: 'text-4xl font-semibold tracking-tight text-gray-900 dark:text-gray-100',
    brandAccent: 'text-indigo-600 dark:text-indigo-400',
    navLink: 'text-xs sm:text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100',
    navLinkActive: 'text-xs sm:text-sm font-semibold text-gray-900 dark:text-gray-100',
    menu: 'hidden items-center gap-6 ml-10 lg:flex',
    actions: 'hidden items-center gap-3 lg:flex',
    center: 'hidden flex-1 lg:block',
    mobileActions: 'flex items-center gap-2 lg:hidden',
    mobileToolbarButton: 'inline-flex h-10 w-10 items-center justify-center rounded-full text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-gray-100',
    mobileMenuButton: 'inline-flex h-10 w-10 items-center justify-center rounded-full text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-gray-100',
    mobileBackdrop: 'fixed inset-0 top-14 z-40 bg-slate-950/20 backdrop-blur-[1px] lg:hidden',
    mobilePanel: 'fixed inset-x-0 top-14 z-50 flex h-[calc(100dvh-3.5rem)] flex-col overflow-y-auto border-b border-gray-200 bg-white/90 px-4 backdrop-blur-2xl shadow-[0_24px_80px_rgba(15,23,42,0.14)] dark:border-gray-700 dark:bg-gray-950/85 lg:hidden',
    mobilePanelOpen: 'translate-y-0 pb-6 pt-4 opacity-100 pointer-events-auto',
    mobilePanelClosed: '-translate-y-3 pb-0 pt-0 opacity-0 pointer-events-none',
    mobileBadgeRow: 'flex items-center justify-between gap-3',
    mobileHint: 'text-xs font-medium uppercase tracking-[0.18em] text-gray-400 dark:text-gray-500',
    mobileMenu: 'mt-4 grid gap-2',
    mobileBottomSpacer: 'flex-1 min-h-6',
    mobileSectionTitle: 'mt-5 mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-gray-500 dark:text-gray-400',
    mobileNavLink: 'flex items-center justify-between rounded-2xl border border-gray-200 px-4 py-3 text-sm font-medium tracking-tight text-gray-700 transition-colors hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700 dark:border-gray-700 dark:text-gray-300 dark:hover:border-indigo-500/50 dark:hover:bg-indigo-500/10 dark:hover:text-indigo-200',
    mobileNavLinkActive: 'flex items-center justify-between rounded-2xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm font-semibold tracking-tight text-indigo-700 dark:border-indigo-500/40 dark:bg-indigo-500/10 dark:text-indigo-200',
    mobileCtaGroup: 'mt-4 grid gap-2 pb-2',
    mobilePrimaryButton: 'inline-flex min-h-11 items-center justify-center rounded-2xl bg-indigo-600 px-4 py-3 text-sm font-medium tracking-tight text-white transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:bg-indigo-500 dark:hover:bg-indigo-600',
    mobileSecondaryButton: 'inline-flex min-h-11 items-center justify-center rounded-2xl border border-gray-200 px-4 py-3 text-sm font-medium tracking-tight text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-gray-800',
    mobileLogoutButton: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl border border-rose-200 px-4 py-3 text-sm font-medium tracking-tight text-rose-600 transition-colors hover:bg-rose-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:ring-offset-2 dark:border-rose-500/30 dark:text-rose-300 dark:hover:bg-rose-500/10',
    primaryButton: 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium bg-indigo-600 text-white transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:bg-indigo-500 dark:hover:bg-indigo-600',
    secondaryButton: 'inline-flex items-center justify-center rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700',
    badge: 'text-xs px-2.5 py-1 rounded-full font-medium inline-flex items-center gap-1.5',
    badgeDot: 'h-1.5 w-1.5 rounded-full bg-current',
    iconButton: 'inline-flex h-9 w-9 items-center justify-center rounded-full text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-gray-100',
    profileMenuWrap: 'relative',
    avatarTrigger: 'inline-flex h-9 items-center gap-1 rounded-full border border-gray-200 bg-white pr-1 text-gray-600 transition-colors hover:bg-gray-50 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-gray-100',
    avatarCaret: 'text-gray-400 dark:text-gray-500',
    avatar: 'h-9 w-9 overflow-hidden rounded-full border border-gray-200 dark:border-gray-600 bg-indigo-50 dark:bg-indigo-900/30 flex items-center justify-center text-sm font-medium text-indigo-600 dark:text-indigo-300',
    avatarImage: 'h-full w-full object-cover',
    dropdown: 'absolute right-6 top-[calc(100%-0.25rem)] z-60 min-w-52 rounded-xl border border-gray-200 bg-white p-1 shadow-lg dark:border-gray-700 dark:bg-gray-900',
    dropdownItem: 'flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-gray-100',
    dropdownDanger: 'text-rose-600 hover:bg-rose-50 hover:text-rose-700 dark:text-rose-300 dark:hover:bg-rose-500/10 dark:hover:text-rose-200',
};
