export const navbarStyles = {
    container: 'sticky top-0 z-[var(--z-nav)] h-14 border-b border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900',
    inner: 'max-w-7xl mx-auto w-full h-full flex items-center justify-between px-6',
    brandLink: 'flex items-center gap-3',
    brandIconWrap: 'w-8 h-8 rounded-lg theme-status-info flex items-center justify-center',
    brandTitle: 'text-xl sm:text-2xl md:text-3xl font-semibold tracking-tight text-gray-900 dark:text-gray-100',    navMenu: 'flex items-center gap-6 ml-8',
    navLinkBase: 'text-xs sm:text-sm md:text-sm font-medium tracking-tight text-gray-600 hover:text-gray-900 transition-colors whitespace-nowrap dark:text-gray-400 dark:hover:text-gray-100', 
    navLinkActive: 'text-sm font-semibold text-gray-900 dark:text-gray-100',
    actions: 'flex items-center gap-3',
    badge: 'text-xs px-2.5 py-1 rounded-full font-medium inline-flex items-center gap-1.5',
    badgeDot: 'h-1.5 w-1.5 rounded-full bg-current',
    ctaGroup: 'flex items-center gap-3',
    primaryButton: 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium theme-primary-bg text-white transition-colors hover:bg-[var(--qb-primary-strong)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2',
    secondaryButton: 'inline-flex items-center justify-center rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700',
    iconButton: 'w-9 h-9 flex items-center justify-center rounded-full text-gray-600 transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--qb-primary)] focus-visible:ring-offset-2 dark:text-gray-300 dark:hover:bg-gray-700',
    profileLink: 'w-9 h-9 overflow-hidden rounded-full border theme-status-info flex items-center justify-center text-sm font-medium',
};
