export const navbar = {
    container: 'h-14 flex items-center justify-between px-6 border-b bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-700 sticky top-0 z-[var(--z-nav)]',
    inner: 'max-w-7xl mx-auto w-full h-full flex items-center justify-between',
    brandLink: 'flex items-center gap-3',
    brandTitle: 'text-xl sm:text-2xl md:text-3xl font-semibold tracking-tight text-gray-900 dark:text-gray-100',
    brandAccent: 'text-indigo-600 dark:text-indigo-400',
    navLink: 'text-xs sm:text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100',
    navLinkActive: 'text-sm font-semibold text-gray-900 dark:text-gray-100',
    logo: 'text-lg font-semibold text-gray-900 dark:text-gray-100',
    menu: 'flex items-center gap-6 ml-8',
    actions: 'flex items-center gap-3',
    ctaGroup: 'flex items-center gap-3',
    primaryButton: 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium bg-indigo-600 text-white transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:bg-indigo-500 dark:hover:bg-indigo-600',
    secondaryButton: 'inline-flex items-center justify-center rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700',
    badge: 'text-xs px-2.5 py-1 rounded-full font-medium inline-flex items-center gap-1.5',
    badgeDot: 'h-1.5 w-1.5 rounded-full bg-current',
    iconButton: 'w-9 h-9 flex items-center justify-center rounded-full text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700',
    avatar: 'w-9 h-9 overflow-hidden rounded-full border border-gray-200 dark:border-gray-600 bg-indigo-50 dark:bg-indigo-900/30 flex items-center justify-center text-sm font-medium text-indigo-600 dark:text-indigo-300',
    avatarImage: 'h-full w-full object-cover',
};
